language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:
  - sleep 15
script:
  - ./gradlew test
